# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY app/package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY app .

# Expose port 3000
EXPOSE 3000

# Define the command to run your app basically node server.js
CMD ["node", "server.js"]
